version: "3.4"
services: 
    nodejs: #docker run -it -v ${PWD}:/work -w /work -p 3001:3001 aimvertor/csharp:1.0.0 /bin/sh
        container_name: nodejs
        image: aimvector/nodejs:1.0.0
        build: 
            context: ./nodejs
            target: dev
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
            - ./nodejs/src/:/work   #For source codes
        ports: 
            - 3001:3001