FROM node:16-alpine3.12 as dev

RUN mkdir /app/
WORKDIR /app/

COPY ./src/package.json /app/package.json
RUN npm install

COPY ./src/ /app/


########## Start New Image ################################
FROM dev as prod

# RUN mkdir /app/
# COPY --from=dev /app/ /app/

CMD node .


